#############
# DEPLOYMENT  
#############
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: web-d
spec:
  selector:   
    matchLabels:
      app: web
  replicas: 2 
  template:   
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: apache
        image: dboffelli/nginx:v1
        ports:
        - containerPort: 80
---

#############
# SERVICIO  
#############
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
     app: web
spec:
  type: ClusterIP
  ports:
  - port: 80
    nodePort: 30002
    protocol: TCP
  selector:
     app: web
