apiVersion: v1
kind: LimitRange
metadata:
  name: recursos
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 1
    defaultRequest:
      memory: 512Mi
      cpu: 0.5
    max:
      memory: 1Gi
      cpu: 1
    min:
      memory: 0.5Gi
      cpu: 0.5
    type: Container
