apiVersion: v1
data:
  index.html: |
    <html>
    <head>
    <title>Configmap</title>
    </head>
    <body>
    <h1>Mira mi index, creado con Configmap</h1>
    </body>
    </html>
kind: ConfigMap
metadata:
  name: nginx-configmap